### ISSUE TITLE
Killed: 9

### ISSUE THREAD

**Issue by yzongy** [jcrozum/pystablemotifs#73]
Hi Jordan,

I am working on large networks with pystablemotifs. As far as I know, the typical workflow to search for controlling strategies is: 
1. Load a Boolean network
2. Calculate its attractors
3. Pick an attractor as the target state
4. Find corresponding controlling strategies with the reprogram_to_trap_spaces function

However, it stopped running possibly due to running out of memory(returning "Killed: 9") when it's searching for attractors with `AttractorRepertoire.from_primes`

Could you please give some tips to avoid this?

The task I am working on is actually a bit different from the typical workflow above since I already have a target state that I want to reach. So if there is a way to skip calculating all possible attractors like:

1. Load a Boolean network
2. Set the target state
3. Find corresponding controlling strategies with the reprogram_to_trap_spaces function

It will be a great help. 

Best,

Bill

**Comment by jcrozum** [comment]
One more thing I forgot to mention: you can also try running `psm.drivers.internal_drivers(target,primes)` directly, but this is a brute force approach. If you are lucky, you might only need a few more overrides to get to the state, in which case it will go relatively fast. Otherwise it could take a very long time.

**Comment by yzongy** [comment]
Thanks Jordan!

I was quite lucky to get the results I wanted with `psm.drivers.internal_drivers(target,primes)`

**Comment by jcrozum** [comment]
Great!
